server:
  port: 8000

# // CONFIGURING FILE SYSTEM BASED CENTRALIZED CONFIGURATION
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:configurations

# // CONFIGURING GIT BASED CENTRALIZED CONFIGURATION
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bekzod-Murotboyev/microservice-config-repository
          search-paths:
            - gateway-service
            - discovery-service
            - auth-service
            - organization-service
            - courier-service
            - reactive-service
            - reactive-secondary-service
          username: Bekzod-Murotboyev
          password: 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