version: '2'

services:
  storage:
    image: openzipkin/zipkin-mysql
    container_name: mysql

  zipkin:
    image: ghcr.io/openzipkin/zipkin:latest
    container_name: zipkin
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-zookeeper:19092

      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql

      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      - MYSQL_DB=zipkin
      - MYSQL_TCP_PORT=3306

    ports:
      - 8004:9411
    depends_on:
      - storage

  dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=mysql

      # Uncomment to see dependency processing logs
      #- ZIPKIN_LOG_LEVEL=DEBUG
      # Uncomment to adjust memory used by the dependencies job
      #- JAVA_OPTS=-verbose:gc -Xms512m -Xmx512m
    depends_on:
      - storage